services:

  #  Backend
  be-eigen-graph:
    container_name: be-eigen-graph
    build:
      context: ./be-eigen-graph
      dockerfile: Be.dev.dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./be-eigen-graph/src:/app/src
      - ./be-eigen-graph/migrations:/app/migrations
      - ./be-eigen-graph/Cargo.toml:/app/Cargo.toml
      - ./be-eigen-graph/Cargo.lock:/app/Cargo.lock
      - /app/target
    depends_on:
      db-eigen-graph:
        condition: service_healthy
      redis-eigen-graph:
        condition: service_started
    environment:
      DATABASE_URL: postgres://root:root@db-eigen-graph:5432/eigen-graph
    networks:
      - eigen-net

  db-eigen-graph:
    container_name: db-eigen-graph
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: eigen-graph
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d eigen-graph" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - .dbdata/postgres/dev/db-eigen-graph/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - eigen-net

  redis-eigen-graph:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - .dbdata/redis/:/data
    networks:
      - eigen-net

  #  Streamer
  be-stream:
    container_name: be-stream
    build:
      context: ./be-stream
      dockerfile: Stream.dev.dockerfile
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./be-stream/src:/app/src
      - ./be-stream/migrations:/app/migrations
      - ./be-stream/Cargo.toml:/app/Cargo.toml
      - ./be-stream/Cargo.lock:/app/Cargo.lock
      - /app/target
    depends_on:
      db-eigen-timescale:
        condition: service_healthy
    environment:
      TIMESCALE_DATABASE_URL: postgres://root:root@db-eigen-timescale:5432/eigen-ts
    networks:
      - eigen-net

  db-eigen-timescale:
    container_name: db-eigen-timescale
    image: timescale/timescaledb:latest-pg17
    restart: always
    environment:
      POSTGRES_DB: eigen-ts
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TIMESCALEDB_TELEMETRY: "off"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d eigen-ts" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - .dbdata/postgres/dev/db-eigen-timescale/:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    networks:
      - eigen-net

  #  Observability
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - eigen-net

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - eigen-net

networks:
  eigen-net:
    driver: bridge