services:

  be-eigen-graph:
    container_name: be-eigen-graph
    build:
      context: ./be-eigen-graph
      dockerfile: Be.dev.dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./be-eigen-graph/src:/app/src
      - ./be-eigen-graph/migrations:/app/migrations
      - ./be-eigen-graph/Cargo.toml:/app/Cargo.toml
      - ./be-eigen-graph/Cargo.lock:/app/Cargo.lock
      - /app/target
    depends_on:
      db-eigen-graph:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://root:root@db-eigen-graph:5432/eigen-graph
    networks:
      - be-eigen-graph-net

  db-eigen-graph:
    container_name: db-eigen-graph
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: eigen-graph
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d eigen-graph" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - .dbdata/postgres/dev/db-eigen-graph/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - be-eigen-graph-net


networks:
  be-eigen-graph-net:
    driver: bridge