[package]
name = "be-eigen-graph"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
reqwest = "0.12.23"
serde = {version="1.0.226", features=["derive"]}
serde_json = "1.0.145"
thiserror = "2.0.16"
tokio = {version="1.47.1", features=["full"]}
